services:
  # universe-timeline-db:
  #   container_name: universe-timeline-db
  #   image: postgres:17
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "${DB_PORT:-5432}:5432"
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  # universe-timeline-api:
  #   container_name: universe-timeline-api
  #   image: ghcr.io/bolinocroustibat/universe-timeline-api:${TAG:-latest}
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   volumes:
  #     - static_volume:/app/static
  #   ports:
  #     - "${API_PORT:-8000}:8000"
  #   environment:
  #     - ENVIRONMENT=${ENVIRONMENT:-unknown}
  #     - DEBUG=${PUBLIC_DEBUG:-false}

  universe-timeline-frontend:
    container_name: universe-timeline-frontend
    image: ghcr.io/bolinocroustibat/universe-timeline:${TAG:-latest}
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./static:/app/static
    environment:
      - VITE_ENV=${VITE_ENV}
      - PUBLIC_DEBUG=${PUBLIC_DEBUG:-false}
